set_property CONFIG_VOLTAGE  3.3  [current_design]
set_property CFGBVS          VCCO [current_design]
set_property PACKAGE_PIN E3       [get_ports clk]
set_property IOSTANDARD  LVCMOS33 [get_ports clk]
create_clock -name sys_clk -period 10.0 [get_ports clk]
set_property PACKAGE_PIN D9       [get_ports rst_n]
set_property IOSTANDARD  LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN C9       [get_ports swap_btn]
set_property IOSTANDARD  LVCMOS33 [get_ports swap_btn]
set_property PACKAGE_PIN H5       [get_ports {led[0]}]
set_property PACKAGE_PIN J5       [get_ports {led[1]}]
set_property PACKAGE_PIN T9       [get_ports {led[2]}]
set_property PACKAGE_PIN T10      [get_ports {led[3]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[*]}]
set_property PACKAGE_PIN E1       [get_ports led_rm]
set_property IOSTANDARD  LVCMOS33 [get_ports led_rm]
set_false_path -through [get_pins inst_rp/*]
